version: '2.1'
orbs:
  unity: game-ci/unity@1.4.0
workflows:
  test-build-with-executors:
    jobs:      
      - unity/build:
          build-target: StandaloneWindows64
          compress: true
          context: unity
          executor:
            editor_version: 2021.3.2f1
            name: unity/windows-2019
            size: large
            target_platform: windows-il2cpp
          name: build-Windows64-il2cpp
          project-path: Unity2D-Demo-Game-CI-CD/src
          step-name: Build StandaloneWindows64 il2cpp
          unity-license-var-name: UNITY_ENCODED_LICENSE
          unity-password-var-name: UNITY_PASSWORD
          unity-username-var-name: UNITY_USERNAME
